language:
  - scala
jdk:
  - openjdk6
scala:
  - 2.11.4
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get -q install valgrind lcov
  - sudo pip install cpp-coveralls
  - wget https://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz
  - tar xf protobuf-2.5.0.tar.gz
  - ( cd protobuf-2.5.0 && ./configure && make -j2 && sudo make install && sudo ldconfig )